boxplot(C_PERC~SITEID, data = soilCN, ylab = "Soil %C")
grid(NA, 5, lwd = 2)

par(mfrow = c(4,1))
boxplot(CNRATIO~SITEID, data = agParams, ylab = "Litter C/N")
grid(NA, 5, lwd = 2)
boxplot(C.RELEASED~SITEID, data = agParams, ylab = "C-CO2 micro g / hr. g dry wt. soil", na.rm=T)
grid(NA, 5, lwd = 2)
boxplot(P_PERC~SITEID, data = agParams, ylab = "Litter %P")
grid(NA, 5, lwd = 2)
boxplot(C_PERC~SITEID, data = soilCN, ylab = "Soil %C")
grid(NA, 5, lwd = 2)

par(mfrow = c(4,1))
boxplot(AVGWT~SITEID, data = agParams, ylab = "Litter Avg Weight per point (gm)")
grid(NA, 5, lwd = 2)
boxplot(BASAREA~SITEID, data = agParams, ylab = "Basal area (m sq./ha)")
grid(NA, 5, lwd = 2)
boxplot(TREEDENS~SITEID, data = agParams, ylab = "Tree Density (trees/ha)")
grid(NA, 5, lwd = 2)
boxplot(C_PERC~SITEID, data = soilCN, ylab = "Soil %C")
grid(NA, 5, lwd = 2)

par(mfrow = c(4,1))
boxplot(CNRATIO~TREATMENT, data = agParams, ylab = "Litter C/N Ratio")
grid(NA, 5, lwd = 2)
boxplot(P_PERC~TREATMENT, data = agParams, ylab = "Litter %P")
grid(NA, 5, lwd = 2)
boxplot(C.RELEASED~TREATMENT, data = agParams, ylab = "C released")
grid(NA, 5, lwd = 2)
boxplot(C_PERC~TREATMENT, data = soilCN, ylab = "Soil %C")
grid(NA, 5, lwd = 2)

par(mfrow = c(3,1))
boxplot(AVGWT~TREATMENT, data = agParams, ylab = "Litter Avg Weight per point (gm)")
grid(NA, 5, lwd = 2)
boxplot(BASAREA~TREATMENT, data = agParams, ylab = "Basal area (m sq./ha)")
grid(NA, 5, lwd = 2)
boxplot(TREEDENS~TREATMENT, data = agParams, ylab = "Tree Density (trees/ha)")
grid(NA, 5, lwd = 2)
